### ISSUE TITLE
`open` method in RasterImage could take CoordinateSystem as parameter

### ISSUE THREAD

**Issue by sebastianbaginski** [magic-lang/ooc-kean#1046]
This would allow us to get rid of explicit assignments to this variable in RasterTests as described in https://github.com/cogneco/ooc-kean/issues/1029
@emilwestergren are you ok with this

**Comment by emilwestergren** [comment]
yes

**Comment by sebastianbaginski** [comment]
I am not sure if this is still needed. @emilwestergren @ziquanyu ?

**Comment by emilwestergren** [comment]
I think it should be there yes.

**Comment by marcusnaslund** [comment]
Hm, the `Image` constructor takes a `CoordinateSystem` as parameter, but none of the derived classes do.

Should we simply add a `CoordinateSystem` parameter to each `open` method and set the system there before returning the new instance, rather than passing the `CoordinateSystem` along the very long chain of constructors (which means we have to edit them also)?
