### ISSUE TITLE
Fix issues that require compiler changes

### ISSUE THREAD

**Issue by marcusnaslund** [magic-lang/ooc-kean#1278]
The following problems cannot be fixed by merely editing the source, but also require `rock` compiler changes.

- [x] **Four functions (`hasNext?`, `hasPrev?`, `instanceOf?`, `inheritsFrom?`) are hardcoded to use question marks**
These should be renamed.

- [x] **Use of `gc_malloc` is hard-coded**
The function `gc_malloc` is still defined in `sdk/Memory.ooc` because nothing builds otherwise. Rock should use `calloc` like everyone else these days. Problems are in `source/rock/middle/FunctionDecl.ooc` and `source/rock/middle/VariableDecl.ooc`.

- [x] **The directory `source/sdk` should be renamed to `source/system`**

- [x] **The three remaining files in `sdk/lang` should move to `sdk/`**
Problems are due to hard-coded references to: `lang_array` in `source/rock/backend/cnaughty/CGenerator.ooc` and `source/rock/middle/Type.ooc`.
`lang_String` in `source/rock/backend/cnaughty/Skeleton.ooc`. `lang_types` in `source/rock/backend/cnaughty/CastWriter.ooc`, `source/rock/backend/cnaughty/CGenerator.ooc`, `source/rock/backend/cnaughty/ClassDeclWriter.ooc`, `source/rock/backend/cnaughty/FunctionCallWriter.ooc`, `source/rock/middle/FuncType.ooc`

- [ ] **Improve C function names**
Original discussion + examples of what it should be are here: #998
Among other things, remove extra and double/triple underscores and remove filename from class names.

**Comment by davidpiuva** [comment]
Alternative solutions to `Improve C function names`

* To get rid of tripple underscores without causing too many conflicts, one could have a name prefix (`magic_`) for hidden functions that is forbidden in identifiers.

* To get rid of double underscores, we must detect when there is a collision between mangled names instead of relying on C99 scoping. During a collision, we can write unique numbers in the names to make the program run and then give compiler warnings to solve before making a PR.

* Double underscores will only occur when a private identifier is placed after single underscore.
`car` and `drive` becomes `car_drive`
`car` and `_steer` becomes `car__steer`
Alternatively, we can forbid underscores in the language but that would break backward compatibility with the whole code base for things that will never be shown outside.

**Comment by marcusnaslund** [comment]
Since all those issues were fixed a lot sooner than I thought (well done @thomasfanell ) I guess it makes more sense to close this and reopen the remaining, old, issue.
