### ISSUE TITLE
Crop for RasterYuv420Semiplanar has flaws with non-rounded floating point numbers

### ISSUE THREAD

**Issue by tomasmahlberg** [magic-lang/ooc-kean#1673]
If I have a crop-box with a start position that is not a rounded floating point number I get a green cross across the cropped image.

```ooc
raster := RasterYuv420Semiplanar open("./test/draw/input/Space.png")
cropBox := FloatBox2D new(FloatPoint2D new(10.00001f, 10.00001f), FloatVector2D new(300.f, 300.f))
raster crop(cropBox) save("output.png")
```

![output](https://cloud.githubusercontent.com/assets/14270984/14789262/0362a960-0b0c-11e6-866b-dc206f4d6d20.png)

@sebastianbaginski I think you worked with this, can you take a look?

**Comment by sebastianbaginski** [comment]
Nice find :) But I don't have time to do that today. If anyone else feel like fixing this then go ahead. Otherwise I'll look into it later this week.

**Comment by marcusnaslund** [comment]
This is strange, since what `RasterYuv420Semiplanar::crop` does first is cast everything to Int and go from there. I will be taking a look.

**Comment by marcusnaslund** [comment]
@sebastianbaginski Is there any reason why the cropping region should be a `FloatBox` instead of an `IntBox`, considering we already do some casting and that proper termination of the for-loops in `cropInto` require a nice rounded number? How would you crop to include 1/10000th of a pixel?

We can solve this easily by adding `region = region round()` in the crop method, but that's still relying a bit too much on floating-point numerics. Better would be to change expected type to `IntBox`.

**Comment by sebastianbaginski** [comment]
I'd say just go with it if it works and doesn't break anything.
